name: "publish"
on:
  push:
    branches:
      - main

jobs:
  publish-tauri:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: install Rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0 libappindicator3-dev librsvg2-dev patchelf flatpak flatpak-builder
          flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
          flatpak --version
          flatpak-builder --version

      - name: Get current date
        run: echo "CURRENT_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
        if: matrix.platform == 'macos-latest' || matrix.platform == 'ubuntu-latest'

      - name: Get current date
        if: matrix.platform == 'windows-latest'
        run: echo "CURRENT_DATE=$(Get-Date -Format "yyyy-MM-dd")" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Get tauri submodule commit
        run: cd submodules/tauri; echo "TAURI_SUBMODULE_COMMIT=$(git rev-parse HEAD)" >> $GITHUB_ENV

      - name: Cache bundler dependencies
        uses: actions/cache@v3
        env:
          cache-name: bundler_deps
        with:
          path: |
            ~/.cache/tauri
            ~/.local/share/flatpak
          key: ${{ matrix.platform }}-stable-${{ env.cache-name }}-${{ hashFiles('**/Cargo.toml', '**/package.json', '**/tauri.conf.json') }}-${{ env.CURRENT_DATE }}
          restore-keys: |
            ${{ matrix.platform }}-stable-${{ env.cache-name }}-${{ hashFiles('**/Cargo.toml', '**/package.json', '**/tauri.conf.json') }}-
            ${{ matrix.platform }}-stable-${{ env.cache-name }}-

      - name: Cache cargo state
        uses: actions/cache@v3
        env:
          cache-name: cargo_state
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ~/.cargo/bin
          key: ${{ matrix.platform }}-stable-${{ env.cache-name }}-${{ hashFiles('**/Cargo.toml') }}-${{ env.CURRENT_DATE }}
          restore-keys: |
            ${{ matrix.platform }}-stable-${{ env.cache-name }}-${{ hashFiles('**/Cargo.toml') }}-
            ${{ matrix.platform }}-stable-${{ env.cache-name }}-

      - name: Cache cargo target
        uses: actions/cache@v3
        env:
          cache-name: cargo_target
        with:
          path: src-tauri/target
          # Add date to the cache to keep it up to date
          key: ${{ matrix.platform }}-stable-${{ env.cache-name }}-${{ hashFiles('src-tauri/Cargo.lock') }}-${{ env.CURRENT_DATE }}
          # Restore from outdated cache for speed
          restore-keys: |
            ${{ matrix.platform }}-stable-${{ env.cache-name }}-${{ hashFiles('src-tauri/Cargo.lock') }}
            ${{ matrix.platform }}-stable-${{ env.cache-name }}-

      - name: Cache cargo-tauri
        id: cargo-tauri-cache
        uses: actions/cache@v3
        env:
          cache-name: cargo_cargo-tauri
        with:
          path: ~/.cargo/bin/cargo-tauri
          key: ${{ matrix.platform }}-stable-${{ env.cache-name }}-${{ env.TAURI_SUBMODULE_COMMIT }}

      - name: install local tauri-cli
        if: steps.cargo-tauri-cache.outputs.cache-hit != 'true'
        run: yarn setup-cli

      - name: install app dependencies and build it
        run: yarn && yarn build

      - uses: beanow/tauri-action@dev
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tauriScript: cargo tauri
          args: --verbose
          tagName: poc-v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version
          releaseName: "POC v__VERSION__"
          releaseBody: "See the assets to download this version and install."
          releaseDraft: true
          prerelease: false
